# Generated by Django 3.2.5 on 2021-08-19 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='fecha_at',
            new_name='fecha',
        ),
    ]
