# Generated by Django 3.2.5 on 2021-08-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_fecha_at_show_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.CharField(default='Descripcion', max_length=250),
            preserve_default=False,
        ),
    ]
