# Generated by Django 3.2.5 on 2021-08-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_show_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='description',
        ),
        migrations.AddField(
            model_name='show',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
