# Generated by Django 3.2.5 on 2021-08-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210818_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='descripcion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
