# Generated by Django 3.2.5 on 2021-08-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_show_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='descripcion',
            field=models.CharField(default='fecha', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
