# Generated by Django 3.2.5 on 2021-08-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210819_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
